.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SCVIM 1 "Nov 18, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
scvim_make_help \- strip SuperCollider HTML help to text, for use with scvim
.SH SYNOPSIS
.B scvim_make_help
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B scvim_make_help
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBscvim_make_help\fP is a script that strips SuperCollider HTML help to text
format, for use with scvim. Users do NOT normally need to invoke it, since it
is called by the main \fBscvim\fP script upon first run.
The stripped files are placed in ~/.scvim by default, but this can be overridden
by specifying SCVIM_CACHE_DIR environment variable.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-s \-\-source\-dir directory
Specify the soruce directory to search for HTML help files.
.TP
.B \-d \-\-dest\-dir directory
The Destination Directory for the processed Help Files.
.TP
.B \-c \-\-clean
Clean the Destination Directory before building the helpfiles.
.TP
.B \-f \-\-force
Do not prompt to see if the user is sure about deleting files.
.TP
.B \-h \-\-help
Show summary of options.
.SH SEE ALSO
.BR scvim (1)
.br
.I /usr/share/doc/supercollider\-vim/README.scvim
.SH AUTHOR
scvim was written by Alex Norman <alex at x37v dot info>.
.PP
This manual page was written by Dan Stowell <danstowell@users.sourceforge.net>,
for the Ubuntu project (but may be used by others).
